version: '3.8'

services:
  # MySQL Database (replaces XAMPP MySQL)
  mysql:
    image: mysql:8.0
    container_name: hanulms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hanulms
      MYSQL_USER: hanulms_user
      MYSQL_PASSWORD: hanulms_password
    ports:
      - "3306:3306"  # Same port as XAMPP for easy transition
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hanulms-network

  # phpMyAdmin (replaces XAMPP phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hanulms-phpmyadmin
    ports:
      - "8081:80"  # Different from your Spring Boot port
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - hanulms-network

  # MinIO Object Storage (new addition)
  minio:
    image: minio/minio
    container_name: hanulms-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Web Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    networks:
      - hanulms-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  # Auto-create MinIO bucket
  minio-init:
    image: minio/mc
    container_name: hanulms-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb myminio/hanulms --ignore-existing;
      /usr/bin/mc policy set public myminio/hanulms;
      exit 0;
      "
    networks:
      - hanulms-network

volumes:
  mysql_data:
  minio_data:

networks:
  hanulms-network:
    driver: bridge